name: chem274A_lab3
channels:
  - conda-forge
dependencies:
  - python=3.12  #
  - numpy
  - matplotlib  
  - openmm
  - pandas
  - mdtraj
  - mdanalysis
  - ambertools
  - packmol
  - pip
  - pip:
      - nglview  